name: Multi-arch kernel build

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build and push multi-arch kernel
    runs-on: ubuntu-latest
    container:
       # The following actions are required to avoid contaimer image pull error.
       # - https://github.com/users/TaichiKageyama/packages/container/kernel-build/settings
       #     + Manage Actions access
       #         * Add Repository: sandbox 
       image: ghcr.io/taichikageyama/kernel-build:20230106-1
       credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /CCACHE:/CCACHE
        - /DATA:/DATA
        - /SRC:/SRC
    steps:
      - name: login check
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Check1
        run: |
          echo $GITHUB_WORKSPACE
          echo ${{ github.repository_owner }}
          ls /
          ls /DATA
          ls /SRC
          ls /CCACHE

      - name: kernel-ccache
        id: kernel-ccache
        uses: actions/cache@v3
        with:
          path: /CCACHE
          key: ccache

      - name: Check2
        run: |
          ls /CCACHE
