---
name: Multi-arch kernel build
on:  # yamllint disable-line rule:truthy
  # - push
  - workflow_dispatch
jobs:
  build:
    name: Build and push multi-arch kernel
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - {kernel: kernel, arch: arm, defconfig: bcmrpi_defconfig}
          - {kernel: kernel7, arch: arm, defconfig: bcm2709_defconfig}
          - {kernel: kernel7l, arch: arm, defconfig: bcm2711_defconfig}
          - {kernel: kernel8, arch: arm64, defconfig: bcm2711_defconfig}
    container:
      # The following actions are required
      #   to avoid contaimer image pull error.
      # - https://$GITHUB_OWNER/packages/container/kernel-build/settings
      #     + Manage Actions access
      #         * Add Repository: sandbox
      image: ghcr.io/taichikageyama/kernel-build:20230106-1
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /CCACHE-${{ matrix.kernel }}:/CCACHE
        - /DATA-${{ matrix.kernel }}:/DATA
        - /SRC-${{ matrix.kernel }}:/SRC
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Check1
        run: |
          set -x
          echo $GITHUB_WORKSPACE
          echo ${{ github.repository_owner }}
          ls /
          ls /DATA
          ls /SRC
          ls /CCACHE
          pwd
          echo "${{ matrix.kernel }}" > /DATA/test.txt
          set +x
      - name: kernel-ccache
        id: kernel-ccache
        uses: actions/cache@v3
        with:
          path: /CCACHE
          key: ccache

      - name: Check2
        run: |
          ls /CCACHE

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.kernel }}
          path: /DATA
